### PR TITLE
enable multiline string environment variables

### PR DESCRIPTION
**Pull request by amy**
https://github.com/rancher/rancher/issues/9305

### CODE REVIEW

**Comment by cjellick** [comment]
A reopening of https://github.com/rancher/rancher-compose-executor/pull/73 (after it got auto-closed because I deleted the v1.6 branch)

**Comment by cjellick** [comment]
Per offline discussion, need to change the UX to use `\` at the end of a line to indicate multiline, instead of wrapping the value in quotes

**Comment by amy** [comment]
Per offline discussion the following UX will be implemented:

Have users suffix environment files with `.yaml`, `.yml`, or `.json` and unmarshall with their respective formats. 

All values that are not a number, bool, or string should result in an error.
Number and bool values must be converted to a string.

**Comment by cjellick** [comment]
was replaced by a better PR

**Pull request closed without merging**
