### PR TITLE
Add ability to create infrastructure stacks

### PR DESCRIPTION
**Pull request by joshwget**
Interested in this feature primarily for development. Being able to launch custom versions of infrastructure services such as Kubernetes via the Rancher CLI would be a lot faster than going through catalog.

### CODE REVIEW

**Comment by cjellick** [comment]
Need context on when/where/how this will be used.

**Comment by cjellick** [comment]
we have the --system flag on `rancher stack create`. seems like it would be more consistent to use that flag

**Comment by joshwget** [comment]
Updated with context. I don't think we use the term "system" anymore in the UI so maybe we should change the `rancher stack create` flag instead.

**Comment by deniseschannon** [comment]
Per @ibuildthecloud - Preferred method currently is to create a stack using rancher CLI that creates a system stack and then using up to call that stack.

**Pull request closed without merging**
