### PR TITLE
don't set error transitioning for stack.upgrade

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/10451

**Comment by cjellick** [comment]
Can you show what this causes to happen in the specific use case mentioned in the bug? Like, what is the behavior before the fix and what is it after the fix

**Comment by StrongMonkey** [comment]
@cjellick It is described in [here](https://github.com/rancher/rancher/issues/10451#issuecomment-357773092)

**Comment by cjellick** [comment]
I think @alena1108 should review this code because you are reversing the behavior that she implemented. Should figure out her reasons for originally having it set to false

**Comment by StrongMonkey** [comment]
@cjellick good catch. @alena1108 Could you review this pr to see why we set it to true originally?

**Comment by alena1108** [comment]
LGTM. It makes sense to send `error=true` to publishTransitioningReply only in Create case. As in Upgrade state the stack will be stuck in Upgrading (no transition to error), and we already propagate the error message.

**Pull request merged**
