### PR TITLE
Changes to add drain timeout field to rancher_compose

### PR DESCRIPTION
**Pull request by prachidamle**
The PR is WIP because:

1) The Trash&Vendor changes depend on two go-rancher PRs to be merged:

https://github.com/rancher/go-rancher/pull/191 (add drain_timeout_ms to go-rancher)

and https://github.com/rancher/go-rancher/pull/192 (fix build failure due to V3)

2) This also needs a change to bump Cattle release to get the relevent changes in Cattle, after they are merged in Cattle

https://github.com/rancher/rancher/issues/2777

### CODE REVIEW

**Comment by prachidamle** [comment]
@cjellick  can you pls review.

**Comment by cjellick** [comment]
It seems not right that this would add so many files from go-rancher. any idea why i added all of v3?

**Comment by prachidamle** [comment]
@cjellick That is because, rancher-compose-executor/v1.6 branch does not have go-rancher/v3 folder (present in master branch of go-rancher) added yet. This is the first PR adding it.

https://github.com/rancher/rancher-compose-executor/tree/v1.6/vendor/github.com/rancher/go-rancher

**Comment by joshwget** [comment]
@prachidamle Any chance you accidentally imported v3 somewhere? I'd expect trash to not vendor this if it was never imported

**Comment by prachidamle** [comment]
@joshwget @cjellick  I do not add any v3 ref, but I see that go-rancher master code, has imported v3 for this file:
https://github.com/rancher/go-rancher/blob/master/hostaccess/instance.go#L7

This most likely makes trash to vendor in entire v3. This also causes build failure for compose.

That should get resolved, after @StrongMonkey's fix for this is put in go-rancher https://github.com/rancher/go-rancher/pull/192/

So 1. Merge @StrongMonkey's fix to go-rancher
 2. Then merge my go-rancher PR 
3. Then I am sure when I point to go-rancher in compose to latest, trash wont add v3.

That's what I meant with "The Trash&Vendor changes depend on two go-rancher PRs to be merged" in my opening comment.

**Comment by cjellick** [comment]
closing in favor of https://github.com/rancher/rancher-compose-executor/pull/128

**Pull request closed without merging**
