### PR TITLE
rancher-compose.yml mem_limit

### PR DESCRIPTION
**Pull request by carolynhu**
https://github.com/rancher/rancher/issues/3554

### CODE REVIEW

**Comment by yasker** [comment]
@joshwget
Can we use the newer version of `libcompose` in vendor instead? I thought we suppose to keep sync with it.

@carolynhu 
Don't add changes then remove it. In this case, one commit should be enough. You can amend your original PR.

Ideally, one commit should get one thing done. It should be clear, meaningful, easy to understand, incremental (means works by itself), and don't break build or functionality.

**Comment by joshwget** [comment]
Copying the `yaml` package was intended. I'm trying to move away from the dependency on libcompose.

**Comment by yasker** [comment]
@joshwget I see.

@carolynhu 
Since we decide to move one package under our control, we need to do it in an understandable way:
1. The first commit: copy the files. Only move, no modification or anything. So when others read about it, they know functionality doesn't change.
2. The second commit: update our source code to point to the new package. If necessary, update vendor.conf, remove the old dependency code in vendor directory.
3. Any additional change in the additional commits.

You can split the second commit into two commits as well. The point is, the reader of commits log should know what's happened exactly without second guessing. Each commit gets one and only one thing done. Everything in one commit is logically coherent, easy to understand, and hard to separate into another commit.

**Comment by yasker** [comment]
Why permission of file changed back and forth?

**Pull request closed without merging**
