### PR TITLE
add templates .Stack.Name

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by carolynhu** [comment]
https://github.com/rancher/rancher/issues/3393

**Comment by joshwget** [comment]
Can you merge `StackInfo` and `ReleaseInfo` into one struct named `StackInfo`? And then expose it as both `Release` and `Stack` so that `.Stack.Version` and `.Release.Name` work?

**Comment by carolynhu** [comment]
@joshwget OK

**Comment by StrongMonkey** [comment]
closing in favor of https://github.com/rancher/rancher-compose-executor/pull/64

**Pull request closed without merging**
